!function(e){var n={};function r(o){if(n[o])return n[o].exports;var _=n[o]={i:o,l:!1,exports:{}};return e[o].call(_.exports,_,_.exports,r),_.l=!0,_.exports}r.m=e,r.c=n,r.d=function(e,n,o){r.o(e,n)||Object.defineProperty(e,n,{enumerable:!0,get:o})},r.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},r.t=function(e,n){if(1&n&&(e=r(e)),8&n)return e;if(4&n&&"object"==typeof e&&e&&e.__esModule)return e;var o=Object.create(null);if(r.r(o),Object.defineProperty(o,"default",{enumerable:!0,value:e}),2&n&&"string"!=typeof e)for(var _ in e)r.d(o,_,function(n){return e[n]}.bind(null,_));return o},r.n=function(e){var n=e&&e.__esModule?function(){return e.default}:function(){return e};return r.d(n,"a",n),n},r.o=function(e,n){return Object.prototype.hasOwnProperty.call(e,n)},r.p="",r(r.s="./src/js/main.js")}({"./src/js/main.js":
/*!************************!*\
  !*** ./src/js/main.js ***!
  \************************/
/*! no exports provided */function(module,__webpack_exports__,__webpack_require__){"use strict";eval('__webpack_require__.r(__webpack_exports__);\n/* harmony import */ var _modules_map__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ./modules/map */ "./src/js/modules/map.js");\n/* harmony import */ var _modules_func__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! ./modules/func */ "./src/js/modules/func.js");\n\n\n\n //calc\n\nObject(_modules_map__WEBPACK_IMPORTED_MODULE_0__["default"])();\nObject(_modules_func__WEBPACK_IMPORTED_MODULE_1__["default"])();\n\n//# sourceURL=webpack:///./src/js/main.js?')},"./src/js/modules/func.js":
/*!********************************!*\
  !*** ./src/js/modules/func.js ***!
  \********************************/
/*! exports provided: default */function(module,__webpack_exports__,__webpack_require__){"use strict";eval("__webpack_require__.r(__webpack_exports__);\nvar asd = function asd() {\n  console.log('asdsdfs');\n};\n\n/* harmony default export */ __webpack_exports__[\"default\"] = (asd);\n\n//# sourceURL=webpack:///./src/js/modules/func.js?")},"./src/js/modules/map.js":
/*!*******************************!*\
  !*** ./src/js/modules/map.js ***!
  \*******************************/
/*! exports provided: default */function(module,__webpack_exports__,__webpack_require__){"use strict";eval("__webpack_require__.r(__webpack_exports__);\nvar map = function map() {\n  /* myMap */\n  ymaps.ready(init);\n  var myMap, myPlacemark1;\n\n  function init() {\n    myMap = new ymaps.Map(\"map\", {\n      center: [44.504216306347296, 34.15167827740982],\n      zoom: 17,\n      controls: ['smallMapDefaultSet']\n    });\n    myMap.controls.add('routeEditor');\n    myMap.controls.remove('geolocationControl').remove('searchControl').remove('trafficControl').remove('rulerControl');\n    myMap.behaviors.disable(['drag', 'scrollZoom']);\n    var myPin = new ymaps.GeoObjectCollection({}, {\n      preset: 'islands#orangeDotIcon',\n      draggable: false\n    });\n    myPlacemark1 = new ymaps.Placemark([44.504216306347296, 34.15167827740982], {\n      balloonContentHeader: '<span class=\"map-color\">Строительная компания \"Оптима\"</span>',\n      balloonContentFooter: 'Республика Крым, г.Ялта, ул. Южнобережное шоссе, 38',\n      hintContent: 'Строительная компания \"Оптима\"'\n    });\n    myPin.add(myPlacemark1);\n    myMap.geoObjects.add(myPin);\n  }\n  /* //myMap */\n\n};\n\n/* harmony default export */ __webpack_exports__[\"default\"] = (map);\n\n//# sourceURL=webpack:///./src/js/modules/map.js?")}});
//# sourceMappingURL=main.js.map
